server:
  port: 8083

spring:
  application:
    name: traffic-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/smartmove
    username: lina
    password: lina

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

tomtom:
  api:
    key: ah8HOxL738TmMMIjXhXvGdTQrSDqsAq3
